### ISSUE TITLE
Quick reacts invisible 2.0.0

### ISSUE THREAD

**Issue by jh34ghu43gu** [LancersBucket/plugin-RemoveChatButtons#6]
The emotes on quick reacts are invisible after updating to version 2.0.0

![Image](https://github.com/user-attachments/assets/deb4c213-95ad-48c9-be08-0eec8290d3cd)

Had both remove reaction button and super reaction button settings (under message actions) on and off and didn't change anything. 

Turning the plugin off made them return.

Would also just like a button to block out that menu section (keeping reply etc) since half the time I press it it's on accident when trying to click discord back into focus.

Thanks for removing the other plugin dependency 👍

**Comment by jh34ghu43gu** [comment]
> Fixed in v2.0.1. Also separated the Add Reaction button toggle and Quick Reaction toggle into two separate toggles so you can hide that section now.

Doesn't seem to be fixed for me and the quick reaction toggle doesn't do anything. I'm on stable 368753 and BD version 1.12.1. Disabled all other plugins and themes to check that it was still broken.

**Comment by LancersBucket** [comment]
Should now be fixed in v2.0.2.

**Comment by ninomae-inanis** [comment]
Using v2.0.2 the emotes are now visible, however the remove quick reactions toggle still does nothing

**Comment by LancersBucket** [comment]
Hopefully finally fixed in v2.0.3. You may have to re-enable the toggle to hide it if you had it enabled prior to the update.
